//-------------------------------------------------------------------------
// File        : tb_top.sv
// Description : Top-level testbench module. Generates the clock and reset, 
//               instantiates the FIFO DUT and interface, and starts the 
//               verification environment.
//-------------------------------------------------------------------------


`include "interface.sv"   
`include "transaction.sv"
`include "generator.sv"
`include "driver.sv"
`include "coverage.sv"
`include "monitor.sv"
`include "scoreboard.sv"
`include "environment.sv"

module tb_top;

  logic clk = 0;
  always #5 clk = ~clk;

  fifo_if intf (clk);

  sync_fifo dut (
    .clk      (clk),
    .reset_n  (intf.reset_n),
    .wr_en    (intf.wr_en),
    .rd_en    (intf.rd_en),
    .data_in  (intf.data_in),
    .data_out (intf.data_out),
    .full     (intf.full),
    .empty    (intf.empty)
  );

  environment env;

    initial begin
      intf.reset_n = 0;
      #20;
      intf.reset_n = 1;
    end
 
    initial begin
      $dumpfile("dump.vcd");
      $dumpvars;

      env = new(intf, 100); // Edit num_transactions to change number of transactions generated by the generator
      env.run();

      $finish;
    end

endmodule